"""
Deterministic, explainable right-sizing recommendation engine.

Rules (all values in millicores / MiB):
  CPU  recommendation  = max(p95_cpu  * CPU_SCALE,  CPU_FLOOR_M)
  MEM  recommendation  = max(p95_mem  * MEM_SCALE,  MEM_FLOOR_MIB)

Confidence:
  high   – historical P95 metrics available
  medium – only current (live) metrics available
  low    – no metrics at all

Risk:
  high   – workload is in a system namespace OR is a StatefulSet with 1 replica
  medium – Deployment with ≥ 3 replicas  OR  StatefulSet
  low    – everything else
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass, field
from typing import Optional

from engine.cost import estimate_savings

CPU_SCALE = 1.5
MEM_SCALE = 1.3
CPU_FLOOR_M = 10
MEM_FLOOR_MIB = 32
IDLE_CPU_THRESHOLD_M = 5
IDLE_MEM_THRESHOLD_MIB = 64

SYSTEM_NAMESPACES = {"kube-system", "kube-public", "kube-node-lease", "cert-manager", "ingress-nginx"}

FLAG_OVER_CPU = "over_provisioned_cpu"
FLAG_OVER_MEM = "over_provisioned_memory"
FLAG_MISSING_REQUESTS = "missing_requests"
FLAG_MISSING_LIMITS = "missing_limits"
FLAG_IDLE = "idle_workload"
FLAG_HIGH_RISK = "high_risk"


@dataclass
class ContainerMetrics:
    name: str
    cpu_request_m: Optional[int]
    cpu_limit_m: Optional[int]
    memory_request_mib: Optional[int]
    memory_limit_mib: Optional[int]
    cpu_usage_p95_m: Optional[int]
    memory_usage_p95_mib: Optional[int]
    cpu_usage_current_m: Optional[int]
    memory_usage_current_mib: Optional[int]
    has_metrics: bool = False
    has_historical_metrics: bool = False


@dataclass
class WorkloadContext:
    workload_id: int
    workload_name: str
    namespace: str
    kind: str
    replicas: int
    is_system_namespace: bool = False
    containers: list[ContainerMetrics] = field(default_factory=list)
    node_cpu_m: int = 2000
    node_memory_mib: int = 8192
    node_monthly_cost: Optional[float] = None


@dataclass
class RecommendationResult:
    workload_id: int
    workload_name: str
    namespace: str
    kind: str
    container_name: str
    flag_type: str
    confidence: str
    risk: str
    explanation: str
    current_cpu_request_m: Optional[int]
    current_cpu_limit_m: Optional[int]
    current_memory_request_mib: Optional[int]
    current_memory_limit_mib: Optional[int]
    recommended_cpu_request_m: Optional[int]
    recommended_cpu_limit_m: Optional[int]
    recommended_memory_request_mib: Optional[int]
    recommended_memory_limit_mib: Optional[int]
    estimated_monthly_savings_usd: float
    is_estimated: bool
    yaml_patch: Optional[str]
    kubectl_command: Optional[str]


def _confidence(c: ContainerMetrics) -> str:
    if c.has_historical_metrics and c.cpu_usage_p95_m is not None:
        return "high"
    if c.has_metrics and c.cpu_usage_current_m is not None:
        return "medium"
    return "low"


def _risk(ctx: WorkloadContext) -> str:
    if ctx.is_system_namespace or SYSTEM_NAMESPACES.intersection({ctx.namespace}):
        return "high"
    if ctx.kind == "StatefulSet":
        return "high" if ctx.replicas == 1 else "medium"
    if ctx.replicas >= 3:
        return "medium"
    return "low"


def _best_cpu(c: ContainerMetrics) -> Optional[int]:
    if c.cpu_usage_p95_m is not None:
        return c.cpu_usage_p95_m
    if c.cpu_usage_current_m is not None:
        return c.cpu_usage_current_m
    return None


def _best_mem(c: ContainerMetrics) -> Optional[int]:
    if c.memory_usage_p95_mib is not None:
        return c.memory_usage_p95_mib
    if c.memory_usage_current_mib is not None:
        return c.memory_usage_current_mib
    return None


def _recommended_cpu(usage_m: int) -> int:
    return max(int(usage_m * CPU_SCALE), CPU_FLOOR_M)


def _recommended_mem(usage_mib: int) -> int:
    return max(int(usage_mib * MEM_SCALE), MEM_FLOOR_MIB)


def _yaml_patch(
    namespace: str,
    workload_name: str,
    kind: str,
    container_name: str,
    cpu_req: Optional[int],
    cpu_lim: Optional[int],
    mem_req: Optional[int],
    mem_lim: Optional[int],
) -> str:
    cpu_req_str = f"{cpu_req}m" if cpu_req is not None else "~"
    cpu_lim_str = f"{cpu_lim}m" if cpu_lim is not None else "~"
    mem_req_str = f"{mem_req}Mi" if mem_req is not None else "~"
    mem_lim_str = f"{mem_lim}Mi" if mem_lim is not None else "~"
    kind_lower = kind.lower()
    return textwrap.dedent(f"""\
        # Advisory patch — review before applying
        # Generated by KubeWise (read-only, not auto-applied)
        apiVersion: apps/v1
        kind: {kind}
        metadata:
          name: {workload_name}
          namespace: {namespace}
        spec:
          template:
            spec:
              containers:
              - name: {container_name}
                resources:
                  requests:
                    cpu: "{cpu_req_str}"
                    memory: "{mem_req_str}"
                  limits:
                    cpu: "{cpu_lim_str}"
                    memory: "{mem_lim_str}"
    """)


def _kubectl_cmd(
    namespace: str,
    workload_name: str,
    kind: str,
    container_name: str,
    cpu_req: Optional[int],
    mem_req: Optional[int],
) -> str:
    cpu_str = f"{cpu_req}m" if cpu_req is not None else "UNCHANGED"
    mem_str = f"{mem_req}Mi" if mem_req is not None else "UNCHANGED"
    kind_lower = kind.lower()
    return (
        f"kubectl set resources {kind_lower}/{workload_name} "
        f"-n {namespace} "
        f"-c {container_name} "
        f"--requests=cpu={cpu_str},memory={mem_str}"
    )


def analyze_workload(ctx: WorkloadContext) -> list[RecommendationResult]:
    if ctx.is_system_namespace or ctx.namespace in SYSTEM_NAMESPACES:
        return []
    results: list[RecommendationResult] = []
    risk = _risk(ctx)

    for c in ctx.containers:
        conf = _confidence(c)
        best_cpu = _best_cpu(c)
        best_mem = _best_mem(c)

        rec_cpu: Optional[int] = None
        rec_mem: Optional[int] = None

        flags: list[tuple[str, str, Optional[int], Optional[int], Optional[int], Optional[int]]] = []

        # ── Missing requests ────────────────────────────────────────────────
        if c.cpu_request_m is None or c.memory_request_mib is None:
            rec_cpu = _recommended_cpu(best_cpu) if best_cpu else CPU_FLOOR_M * 10
            rec_mem = _recommended_mem(best_mem) if best_mem else MEM_FLOOR_MIB * 4
            explanation = (
                f"Container '{c.name}' in {ctx.workload_name} has no resource requests defined. "
                "Without requests the Kubernetes scheduler cannot make informed placement decisions, "
                "and the container competes for resources at the node level. "
                f"Recommended: cpu={rec_cpu}m, memory={rec_mem}Mi based on "
                + ("observed usage." if best_cpu else "conservative defaults (no metrics available).")
            )
            flags.append((FLAG_MISSING_REQUESTS, explanation, rec_cpu, None, rec_mem, None))

        # ── Missing limits ──────────────────────────────────────────────────
        if c.cpu_limit_m is None or c.memory_limit_mib is None:
            rec_cpu_l = int((rec_cpu or (c.cpu_request_m or CPU_FLOOR_M * 10)) * 2)
            rec_mem_l = int((rec_mem or (c.memory_request_mib or MEM_FLOOR_MIB * 4)) * 1.5)
            explanation = (
                f"Container '{c.name}' has no resource limits set. "
                "A container without limits can consume unbounded node resources, "
                "causing noisy-neighbour issues and potential node pressure evictions. "
                f"Recommended limits: cpu={rec_cpu_l}m, memory={rec_mem_l}Mi."
            )
            flags.append((FLAG_MISSING_LIMITS, explanation, None, rec_cpu_l, None, rec_mem_l))

        # ── Idle workload ───────────────────────────────────────────────────
        if (
            best_cpu is not None
            and best_mem is not None
            and best_cpu <= IDLE_CPU_THRESHOLD_M
            and best_mem <= IDLE_MEM_THRESHOLD_MIB
        ):
            explanation = (
                f"Workload '{ctx.workload_name}' (container '{c.name}') appears idle. "
                f"CPU P95={best_cpu}m (threshold {IDLE_CPU_THRESHOLD_M}m), "
                f"memory P95={best_mem}Mi (threshold {IDLE_MEM_THRESHOLD_MIB}Mi). "
                "Consider scaling to zero or removing this workload if it is no longer needed."
            )
            flags.append((FLAG_IDLE, explanation, CPU_FLOOR_M, CPU_FLOOR_M * 2, MEM_FLOOR_MIB, MEM_FLOOR_MIB * 2))

        # ── Over-provisioned CPU ────────────────────────────────────────────
        if (
            c.cpu_request_m is not None
            and best_cpu is not None
            and c.cpu_request_m > 0
        ):
            safe_cpu = _recommended_cpu(best_cpu)
            if safe_cpu < c.cpu_request_m * 0.7:
                waste_pct = round((1 - safe_cpu / c.cpu_request_m) * 100, 1)
                explanation = (
                    f"Container '{c.name}' requests {c.cpu_request_m}m CPU but P95 usage is "
                    f"{best_cpu}m — approximately {waste_pct}% over-provisioned. "
                    f"Recommended request: {safe_cpu}m (P95 × {CPU_SCALE} with floor {CPU_FLOOR_M}m). "
                    + ("Values derived from historical P95 data." if c.has_historical_metrics else "Based on current metrics only — confidence is medium.")
                )
                rec_cpu = safe_cpu
                flags.append((FLAG_OVER_CPU, explanation, safe_cpu, c.cpu_limit_m, c.memory_request_mib, c.memory_limit_mib))

        # ── Over-provisioned memory ─────────────────────────────────────────
        if (
            c.memory_request_mib is not None
            and best_mem is not None
            and c.memory_request_mib > 0
        ):
            safe_mem = _recommended_mem(best_mem)
            if safe_mem < c.memory_request_mib * 0.75:
                waste_pct = round((1 - safe_mem / c.memory_request_mib) * 100, 1)
                explanation = (
                    f"Container '{c.name}' requests {c.memory_request_mib}Mi memory but P95 usage is "
                    f"{best_mem}Mi — approximately {waste_pct}% over-provisioned. "
                    f"Recommended request: {safe_mem}Mi (P95 × {MEM_SCALE} with floor {MEM_FLOOR_MIB}Mi). "
                    + ("Values derived from historical P95 data." if c.has_historical_metrics else "Based on current metrics only — confidence is medium.")
                )
                rec_mem = safe_mem
                flags.append((FLAG_OVER_MEM, explanation, c.cpu_request_m, c.cpu_limit_m, safe_mem, c.memory_limit_mib))

        # ── High-risk warning ───────────────────────────────────────────────
        if risk == "high" and ctx.is_system_namespace:
            explanation = (
                f"Workload '{ctx.workload_name}' runs in the '{ctx.namespace}' namespace "
                "which is classified as a system/critical namespace. "
                "KubeWise will not auto-apply any changes here. "
                "Review all recommendations carefully before manual application."
            )
            flags.append((FLAG_HIGH_RISK, explanation, c.cpu_request_m, c.cpu_limit_m, c.memory_request_mib, c.memory_limit_mib))

        for (flag, expl, r_cpu_req, r_cpu_lim, r_mem_req, r_mem_lim) in flags:
            savings = estimate_savings(
                c.cpu_request_m, r_cpu_req,
                c.memory_request_mib, r_mem_req,
                replicas=ctx.replicas,
                node_cpu_m=ctx.node_cpu_m,
                node_memory_mib=ctx.node_memory_mib,
                node_monthly_cost=ctx.node_monthly_cost,
            )
            yaml = _yaml_patch(
                ctx.namespace, ctx.workload_name, ctx.kind, c.name,
                r_cpu_req, r_cpu_lim, r_mem_req, r_mem_lim,
            )
            kubectl = _kubectl_cmd(
                ctx.namespace, ctx.workload_name, ctx.kind, c.name,
                r_cpu_req, r_mem_req,
            )
            results.append(
                RecommendationResult(
                    workload_id=ctx.workload_id,
                    workload_name=ctx.workload_name,
                    namespace=ctx.namespace,
                    kind=ctx.kind,
                    container_name=c.name,
                    flag_type=flag,
                    confidence=conf,
                    risk=risk,
                    explanation=expl,
                    current_cpu_request_m=c.cpu_request_m,
                    current_cpu_limit_m=c.cpu_limit_m,
                    current_memory_request_mib=c.memory_request_mib,
                    current_memory_limit_mib=c.memory_limit_mib,
                    recommended_cpu_request_m=r_cpu_req,
                    recommended_cpu_limit_m=r_cpu_lim,
                    recommended_memory_request_mib=r_mem_req,
                    recommended_memory_limit_mib=r_mem_lim,
                    estimated_monthly_savings_usd=savings,
                    is_estimated=True,
                    yaml_patch=yaml,
                    kubectl_command=kubectl,
                )
            )

    return results
